title: My Github Pages
description: My Personal Interest of DataScience, Microbiology and Bioinformatics
author: Dicky Bagus
github: https://github.com/dickybagus
about: I am Medical Docter who love anything about technology 
disqus_shortname: dickybagus
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/dickybagus"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/dickybagus"

share:
  twitter_username: 
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "localhost:4000"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
